## Dictionaries of all GRE vocabs I encounter ##

gre_vocabs = {
  'domineering' : 'acting with or showing arrogance or tyranny; imperious',
  'eminent': '1. of high rank, station, or quality; noteworthy. \n2. Outstanding, as in character or performance; distinguished. \n3. Towering or standing out above others; prominent.',
  'unobjectionable': 'Raising no objections; acceptable',
  'conventional': '1. Based on or in accordance with general \nagreement, use, or practice; customary. \n2. Comforming to established practice or accepted standards; traditional',
  'execrable': '1. Deserving of execration; hateful. \n2. Extremely inferior; very bad',
  'bombastic': 'Grandiloquent, pompous speech or writing. \n[grandiloquent: lofty (majestic) in style; Pompous: characterized by \nexcessive self-esteem or exaggerated dignity; pretentious]',
  'critical': '1. Inclined to judge severely and find fault. \n2. Characterized by careful, exact evaluation and judgement',
  'prolific': '1. producing offspring, young, fruit, etc., \nabundantly; highly fruitful. \n2. Highly productive: a prolific writer. \n3. Characterized by abundant production',
  'eclectic': 'Selecting or employing individual elements \nfrom a variety of sources, or styles.',
  'expediency': '1. Appropriateness to the purpose at hand; fitness. \n2. Adherence to self-serving means',
  'indulgence': '1.a. The act or an instance of indulging; gratification. \n  b. The state of being indulgent. \n2.a. The act of indulging in something: e.g. indulgence in irresponsible behavior. \n  b. Something indulged in: e.g. Sports cars are an expensive indulgence. \n3. Liberal or lenient treatment; tolerance: e.g. treated their grandchildren with fond indulgence',
  'calamity': '1. An event that brings terrible loss, lasting \ndistress, or severe affliction; a disaster. \n2. Dire distress resulting from loss or tragedy',
  'regency' : 'A person or group selected to govern in place \nof a monarch or other ruler who is absent, disabled, or still in minority. \n2. The period during which a regent governs',
  'jubilance': '1. Exultingly joyful. \n2. Expressing joy.',
  'mischievous': '1. Causing mischief. [mischief: Behavior that\n causes annoyance in another.] \n2. Playful in a naughty or teasing way. [naughty: 1. behaving disobediently. 2. Indecent; improper.] \n3. Troublesome; irritating: e.g. a mischievous prank. \n4. Causing harm, injury, or damage: e.g. mischievous rumors and falsehoods.',
  'blunt' : '1. Having a dull edge or end; not sharp. \n2. Abrupt and often disconcertingly frank in speech. \n3. Slow to understand or perceive; dull. \n4. Lacking in feeling; insensitive',
  'obtuse': '1.a. Lacking quickness of perception or intellect. \n  b. Characterized by a lack of intelligence or sensitivity: e.g. an obtuse remark. \n  c. Not distinctly felt: e.g. an obtuse pain. \n2.a. Not sharp, pointed, or acute in form; blunt. \n  b. Having a blunt or rounded tip.',
  'abominable': '1. Unequivocally detestable; loathsome: \ne.g. abominable treatment of prisoners. \n2. Thoroughly unpleasent or disagreable: e.g. abominable weather.',
  'barren': '1. Not producing offspring. \n2. Lacking vegetation, especially useful vegetation. \n3. Unproductive results or gains; unprofitable: e.g. barren efforts. \n4. Devoid of something specified: e.g. writing barren of insight.',
  'discreet': '1. Marked by, exercising, or showing prudence and \nwise self-restraint in speech and behavior; circumspect. \n2. Free from ostentation or pretention; modest. [ostentation: pretentious \ndisplay meant to impress others; boastful showiness.]',
  'ripple': '1. wave, tremor, oscillation, or undulation. \n2. Consequence, result, side effect, backlash, sequel, repercussion, or reverbation.',
  'incredulous': '1. skeptical; disbelieving. \n2. Expressive of disbelief: e.g. an incredulous stare.',
  'prodigious': '1. Impressively great in size, force, or extent; enormous. \n2. Extraordinary; marvelous: e.g. a prodigious talent.',
  'stolidity': 'Having or revealing little emotion or sensibility; impassive',
  'exasperation': '1. The act or an instance of exasperating. \n[exasperate: to make very angry or impatient; annoy greatly.] \n2. The state of being exasperated; frustrated annoyance.',
  'commensurate': '1. Of the same size, extent, or duration as another. \n2. Corresponding in size or degree; proportionate.',
  'sidereal': 'relating to the stars or constellations',
  'boisterous': '1. Rough and stormy; violent. \n2. Loud, noisy, and lacking in restraint or discipline.',
  'etiolated': '1. (especially of plants) developed without \nchlorophyll by being deprived of light. \n2. pale, faded, colorless.',
  'singular': 'Being only one; individual',
  'circumscribed': 'subject to limits or subjected to limits',
  'intransigent': 'Refusing to moderate a position, especially \nan extreme position; uncompromising.',
  'comportment': 'conduct; bearing; behavior; demeanor.',
  'incorporate': '1. To unite (one thing) with something else already in existence. \n2. To admit as a member to a corporation or similar organization. \n3. To cause to merge or combine together into a united whole.',
  'alleviate': 'To make (pain, for example) more bearable',
  'recast': '1. To mold again. [mold: to form into a particular shape; give shape to.] \n2. To set down or present (ideas, for example) in a new or different \narrangement: e.g. recast a sentence. \n3. To change the cast of (theatrical production).',
  'delineate': '1. To draw or trace the outline of; sketch out. \n2. To represent pictorially; depict. \n3. To depict in words or gestures; describe.',
  'balk at': '(idiom) to resist and object to something; to shy away from doing something',
  'revel in': '(idiom) to rejoice or celebrate about something.',
  'retaliate': 'to return like for like, especially evil for evil.',
  'ominous': 'menacing; threatening.',
  'discomposure': '1. absence of composure. \n2. anxious embarrassment.',
  'resolute': 'Firm or determined; unwavering.'
}
